language: rust
sudo: false

os: linux
rust: stable

cache: cargo

before_script:
  - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
  - (test -x $HOME/.cargo/bin/mdbook || cargo install --vers "^0.2" mdbook)
  - cargo install-update -a

script:
  - mdbook build

deploy:
  provider: pages
  skip_cleanup: true
  keep-history: false
  local_dir: book/
  github_token: $GITHUB_API_KEY
  on:
    branch: master
