[book]
authors = ["NamsooCho","suhr"]
multilingual = false
src = "src"
title = "Tox Human Docs"

[output.html]
mathjax-support = true
additional-css = ["src/static/table.css"]

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2

[output.linkcheck] # enable the "mdbook-linkcheck" renderer
